#!/bin/bash
# PreCompact hook: snapshot session state before conversation compaction.
#
# Writes a short markdown brief to .claude/session-state.md so the next session
# (or the post-compact continuation) can pick up where we left off:
#   - uncommitted changes
#   - recent commits
#   - today's changed files
#   - current branch
#
# The file is gitignored. Read it back via /start at session kickoff.
# Non-blocking: always exits 0 so compaction is never aborted.

set -uo pipefail

STATE_FILE="$CLAUDE_PROJECT_DIR/.claude/session-state.md"
cd "$CLAUDE_PROJECT_DIR" || exit 0

{
  echo "# Session State"
  echo ""
  echo "> Auto-generated by PreCompact hook at $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo ""
  echo "## Branch"
  echo ""
  echo "\`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)\`"
  echo ""
  echo "## Uncommitted changes"
  echo ""
  if [ -z "$(git status -s 2>/dev/null)" ]; then
    echo "_clean working tree_"
  else
    echo '```'
    git status -s 2>/dev/null
    echo '```'
  fi
  echo ""
  echo "## Recent commits (last 5)"
  echo ""
  echo '```'
  git log -5 --oneline 2>/dev/null || echo "no commits"
  echo '```'
  echo ""
  echo "## Files changed today"
  echo ""
  TODAY_FILES=$(git log --since="00:00" --name-only --pretty=format:"" 2>/dev/null | sort -u | sed '/^$/d')
  if [ -z "$TODAY_FILES" ]; then
    echo "_no commits today_"
  else
    echo '```'
    echo "$TODAY_FILES"
    echo '```'
  fi
} > "$STATE_FILE" 2>/dev/null

exit 0
